# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ec37787af0d8a2e14237bdf2a0a5d92c36dd95994b7faada997e8a3452db1225f9b429791a0abcaec9930d81a0f92f296ebaa6bc8453070adeab3d0ffa45e05

test:
  secret_key_base: 45259873602553906befa4af29dcfcc35810f76afe6e3890883f04130e1f1ddfdcd67eae061a8111f3f291a96b4fe1e62bf334e302e9f373a79bde9687faa9bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
